name: make Data Mart

on: push

jobs:
  build:
    name: make data mart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo $GCP_PROJECT
      
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@master
#        with:
#          project_id: $GCP_PROJECT
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true