name: make Data Mart

on: push

jobs:
  build:
    name: make data mart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hellow, world
        run: echo hello, world!
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Make datasets
        run: bq --location=us mk --force --dataset test_dataset

      - name: Make view
        run: |
          for f in $(find data_marts -type f -name *.sql)
          do
            dataset_name=test_dataset
            view_name=$(echo $f | sed -e "s/.sql//g" -e "s/.*\///g" )
            if [[ view_name =~ table_ ]]
              then
                table_name=$(echo $view_name | sed 's/table_//g')
                bq query --replace --use_legacy_sql=false --destination_table ${dataset_name}.${table_name} < $f
              else
                bq mk --use_legacy_sql=false --view 'select event_name from `valid-progress-257914.analytics_254523623.events_20211105`' test_dataset.test_view
            fi
          done