name: make Data Mart

on: push

jobs:
  build:
    name: make data mart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      
    